import '@/app/ui/global.css';
import { inter } from './ui/fonts';

export const metadata = {
  title: {
    default: 'Acme',
    template: '%s | Acme',
  },
  description: 'Generated by create next app',
  metadataBase: new URL('https://acme.com'),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
